services:
  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    ports:
      - "${HOST_PORT:-8000}:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata: