services:
  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata: